#!/bin/bash
# chkconfig: 2345 85 15
# description:auto_run

export JAVA_HOME=/usr/local/jdk
export PATH=$PATH:$JAVA_HOME/bin
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

RUN_NAME="NetStatus.jar"
JAVA_OPTS=/home/NetStatus.jar

start()
        {
                nohup java -jar $JAVA_OPTS
                exit 0
        }
stop()
        {
                kill -9 'ps -ef | grep $JAVA_OPTS | grep -v stop | awk '{print $2}''
        }

case "$1" in
        start)
                start
        ;;
        stop)
                stop
        ;;
        restart)
                stop
                start
        ;;
        *)
                echo "Userage: $0 {start|stop|restart}"
                exit 1
esac
